### ISSUE TITLE
配置文件开启了Rag，就无法正常启动了。

### ISSUE THREAD

**Issue by smalldeer1982** [wwbin2017/bailing#7]
配置文件中保留了Rag的配置
Rag:
  doc_path: documents/
  emb_model: BAAI/bge-small-zh-v1.5
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-11111111111111111

运行python main.py，最后提示

2024-11-01 15:57:58,094 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /BAAI/bge-small-zh-v1.5/resolve/main/config.json HTTP/1.1" 200 0
2024-11-01 15:57:58,801 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /BAAI/bge-small-zh-v1.5/resolve/main/tokenizer_config.json HTTP/1.1" 200 0
2024-11-01 15:57:59,151 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/BAAI/bge-small-zh-v1.5/revision/main HTTP/1.1" 200 1940
2024-11-01 15:57:59,461 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/BAAI/bge-small-zh-v1.5 HTTP/1.1" 200 1940
2024-11-01 15:57:59,495 - chromadb.telemetry.product.posthog - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2024-11-01 15:57:59,646 - chromadb.config - DEBUG - Starting component System
2024-11-01 15:57:59,646 - chromadb.config - DEBUG - Starting component Posthog
2024-11-01 15:57:59,646 - chromadb.config - DEBUG - Starting component OpenTelemetryClient
2024-11-01 15:57:59,646 - chromadb.config - DEBUG - Starting component SqliteDB
2024-11-01 15:57:59,657 - chromadb.config - DEBUG - Starting component SimpleQuotaEnforcer
2024-11-01 15:57:59,657 - chromadb.config - DEBUG - Starting component SimpleRateLimitEnforcer
2024-11-01 15:57:59,658 - chromadb.config - DEBUG - Starting component LocalSegmentManager
2024-11-01 15:57:59,658 - chromadb.config - DEBUG - Starting component LocalExecutor
2024-11-01 15:57:59,658 - chromadb.config - DEBUG - Starting component SegmentAPI
2024-11-01 15:57:59,685 - chromadb.config - DEBUG - Starting component LocalHnswSegment
(chattts) D:\ChatGpt111\bailing-main>

直接停止运行了。

如果我把Rag注释掉，就可以正常运行了。请教

**Comment by hjxbin** [comment]
您发的邮件我已收到，谢谢您！！！

**Comment by smalldeer1982** [comment]
另外还有一个问题，windows下 ffmpeg识别的问题
2024-11-01 17:27:41,697 - torio._extension.utils - DEBUG - Loading FFmpeg6
2024-11-01 17:27:41,700 - torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
File "D:\anaconda3\envs\chattts\lib\site-packages\torio_extension\utils.py", line 116, in _find_ffmpeg_extension
ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
File "D:\anaconda3\envs\chattts\lib\site-packages\torio_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
_load_lib(lib)
File "D:\anaconda3\envs\chattts\lib\site-packages\torio_extension\utils.py", line 94, in load_libtorch.ops.load_library(path)File "D:\anaconda3\envs\chattts\lib\site-packages\torch_ops.py", line 1295, in load_libraryctypes.CDLL(path)File "D:\anaconda3\envs\chattts\lib\ctypes_init.py", line 374, in init
self._handle = _dlopen(self._name, mode)，这个还是没有解决，不知道如何处理，实际文件是有的，但就是无法识别

**Comment by ibmsun1** [comment]
您好，我也遇到了rag的问题，请问怎么解决的

**Comment by wwbin2017** [comment]
你这可以直接把模型下载到本地，不通过huggingface，另外可以把错误日志发出来看下

**Comment by smalldeer1982** [comment]
我这个huggingface已经下载好了，这个提示信息是正确的，返回的是200
